#!/usr/bin/env php
<?php

use App\BalanceCommand;
use Symfony\Component\Console\Application;

require __DIR__.'/vendor/autoload.php';

$application = new Application();

$application->add(new BalanceCommand());

$application->run();

