#!/usr/bin/env php
<?php

use App\CutCommand;
use Symfony\Component\Console\Application;

require __DIR__.'/vendor/autoload.php';

$application = new Application();

$application->add(new CutCommand());

$application->run();

